"""empty message

Revision ID: 307919aff95
Revises: 983ae6d9dc
Create Date: 2015-10-01 20:38:24.971483

"""

# revision identifiers, used by Alembic.
revision = '307919aff95'
down_revision = '983ae6d9dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
