"""empty message

Revision ID: 4f55200ff0d
Revises: 12fb9eb7605
Create Date: 2015-09-23 20:14:18.425865

"""

# revision identifiers, used by Alembic.
revision = '4f55200ff0d'
down_revision = '12fb9eb7605'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
